Feature/rx java support
johnjohndoe/c3media-base pull request #1
Opened 2017-09-21 23:41 UTC by stefanmedack

This PR encapsulates the current code into an own module `base` and adds an additional module `rx-java-2`

2017-09-22 07:38 UTC, johnjohndoe requested changes
Thank you for this nice feature! :rocket: 

I like you to clean up your branch a bit.
1. Please **squash** the first three commits into **one** since all that happened was a name change of the module. We don't need to keep the history of this decision change.
1. Futher, rebase the last commit into the former to undo changing the **library version** back and forth. I will raise the version as soon as it is suitable.
1. Other changes needed I commented directly.

Please let me know if you need help with rebasing your branches - I can also do that otherwise. Feel free to **force push your branch** to update this pull request.

2017-09-22 07:38 UTC, johnjohndoe commented on rx-java-2/gradle.properties
> +module_artifact_id=rx-java-2
Please use camel-case here: `moduleArtifactId`.

2017-09-22 07:38 UTC, johnjohndoe commented on base/gradle.properties
> +module_artifact_id=base
Please use camel-case here: `moduleArtifactId`.

2017-09-22 07:38 UTC, johnjohndoe commented on README.md
> +    compile "info.metadude.kotlin.library.c3media:base:${version}"
Please remove curly braces around the inline variable since they are actually not needed.

2017-09-22 15:17 UTC, stefanmedack commented
Okay, changed everything you asked for. Feel free to have another look

2017-09-22 21:29 UTC, johnjohndoe requested changes
Thanks for the corrections. Please use `git rebase -i` to clean up your branch. The later corrections should not sit on top of the branch instead should be integrated in the commits which introduced the code change.

I added a few new change requests.

2017-09-22 21:29 UTC, johnjohndoe commented on base/gradle.properties
> +moduleArtifactId=base
Please prefix the artifact id with `c3media-` as it was before. The name of the generated jar file should always state the name of the library such as `c3media-base-0.1.0-SNAPSHOT.jar`. As a result you also have to update the dependency statement to `compile "info.metadude.kotlin.library.c3media:c3media-base:$version"`.

2017-09-22 21:29 UTC, johnjohndoe commented on rx-java-2/gradle.properties
> +moduleArtifactId=rx-java-2
Please prefix the artifact id with `c3media-` as it was before. The name of the generated jar file should always state the name of the library such as `c3media-rx-java-2-0.1.0-SNAPSHOT.jar`. As a result you also have to update the dependency statement to `compile "info.metadude.kotlin.library.c3media:c3media-rx-java-2:$version"`.

2017-09-22 21:29 UTC, johnjohndoe commented on gradle/deploy.gradle
> +            artifactId moduleArtifactId
Rebase interactive your changes into the original commits - don't put the changes on top of the branch.

2017-09-22 21:29 UTC, johnjohndoe commented on README.md
> -    compile "info.metadude.kotlin.library.c3media:base:${version}"
Rebase interactive your changes into the original commits - don't put the changes on top of the branch.

2017-09-22 21:29 UTC, johnjohndoe commented on gradle.properties
> +versionName=0.2.0-SNAPSHOT
Don't change the version here.

2017-09-22 21:29 UTC, johnjohndoe commented on gradle.properties
> +versionName=0.1.0-SNAPSHOT
Don't change the version here.

2017-09-22 21:29 UTC, johnjohndoe commented on gradle.properties
> +versionName=0.4.0-SNAPSHOT
Don't change the version here.

2017-09-23 11:00 UTC, closed without merging

2017-09-23 17:04 UTC, johnjohndoe commented on base/gradle.properties
> +moduleArtifactId=base
Fixed in #2.

2017-09-23 17:05 UTC, johnjohndoe commented on rx-java-2/gradle.properties
> +moduleArtifactId=rx-java-2
Fixed in #2.

2017-09-23 17:05 UTC, johnjohndoe commented on gradle/deploy.gradle
> +            artifactId moduleArtifactId
Fixed in #2.