Closes #4 - removes createdAt field in Event, because it does not exi…
johnjohndoe/c3media-base pull request #5
Opened 2017-10-08 12:57 UTC by stefanmedack

…st in api.media.ccc.de

2017-10-11 22:30 UTC, johnjohndoe requested changes
Please also remove the field from `ProductionApiTest.assertListEvent()`.

2017-10-15 16:51 UTC, stefanmedack commented
I didn't see that, because it was commented out. But it's now removed from the ProducationApiTest too :)

2017-10-16 21:41 UTC, johnjohndoe approved these changes

2017-10-16 21:42 UTC, merged

2017-10-16 21:44 UTC, johnjohndoe commented
I removed the modification of the "recording" test to keep the commit clean, squashed the commits and rebased it. Thank you.